### ISSUE TITLE
Drivers for MT6620 and MT6628 won't build with GCC 4.9.4

### ISSUE THREAD

**Issue by arzam16** [arzam16/mt6577_kernel_Acer_B1_A71#6]
```
In file included from mediatek/kernel/drivers/combo/drv_wlan/mt6620/wlan/os/linux/include/gl_os.h:584:0,
                 from mediatek/kernel/drivers/combo/drv_wlan/mt6620/wlan/include/precomp.h:173,
                 from mediatek/kernel/drivers/combo/drv_wlan/mt6620/wlan/common/wlan_lib.c:948:
mediatek/kernel/drivers/combo/drv_wlan/mt6620/wlan/common/wlan_lib.c: In function ‘wlanReleasePendingOid’:
mediatek/kernel/drivers/combo/drv_wlan/mt6620/wlan/os/linux/include/gl_kal.h:1860:1: error: inlining failed in call to always_inline ‘kalOidComplete’: function body not available
 kalOidComplete (
 ^
mediatek/kernel/drivers/combo/drv_wlan/mt6620/wlan/common/wlan_lib.c:2355:21: error: called from here
                     kalOidComplete(prAdapter->prGlueInfo,
                     ^
```

**Comment by arzam16** [comment]
Fixed in 72995fe0f9a1e30979d2dbe293b4af40add051f0
